// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: orleans_service.proto

#include "orleans_service.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
namespace dodo {
namespace test {
class OrleansRequestDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<OrleansRequest>
      _instance;
} _OrleansRequest_default_instance_;
class OrleansResponseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<OrleansResponse>
      _instance;
} _OrleansResponse_default_instance_;
}  // namespace test
}  // namespace dodo
namespace protobuf_orleans_5fservice_2eproto {
void InitDefaultsOrleansRequestImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  protobuf_gayrpc_2fcore_2fgayrpc_5fmeta_2eproto::InitDefaultsRpcMeta();
  {
    void* ptr = &::dodo::test::_OrleansRequest_default_instance_;
    new (ptr) ::dodo::test::OrleansRequest();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::dodo::test::OrleansRequest::InitAsDefaultInstance();
}

void InitDefaultsOrleansRequest() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsOrleansRequestImpl);
}

void InitDefaultsOrleansResponseImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  protobuf_gayrpc_2fcore_2fgayrpc_5fmeta_2eproto::InitDefaultsRpcMeta();
  {
    void* ptr = &::dodo::test::_OrleansResponse_default_instance_;
    new (ptr) ::dodo::test::OrleansResponse();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::dodo::test::OrleansResponse::InitAsDefaultInstance();
}

void InitDefaultsOrleansResponse() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsOrleansResponseImpl);
}

::google::protobuf::Metadata file_level_metadata[2];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::dodo::test::OrleansRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::dodo::test::OrleansRequest, grain_type_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::dodo::test::OrleansRequest, grain_name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::dodo::test::OrleansRequest, meta_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::dodo::test::OrleansRequest, body_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::dodo::test::OrleansResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::dodo::test::OrleansResponse, meta_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::dodo::test::OrleansResponse, body_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::dodo::test::OrleansRequest)},
  { 9, -1, sizeof(::dodo::test::OrleansResponse)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::dodo::test::_OrleansRequest_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::dodo::test::_OrleansResponse_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "orleans_service.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\025orleans_service.proto\022\tdodo.test\032\037gayr"
      "pc/core/gayrpc_option.proto\032\035gayrpc/core"
      "/gayrpc_meta.proto\"j\n\016OrleansRequest\022\022\n\n"
      "grain_type\030\001 \001(\t\022\022\n\ngrain_name\030\002 \001(\t\022\"\n\004"
      "meta\030\003 \001(\0132\024.gayrpc.core.RpcMeta\022\014\n\004body"
      "\030\004 \001(\t\"C\n\017OrleansResponse\022\"\n\004meta\030\001 \001(\0132"
      "\024.gayrpc.core.RpcMeta\022\014\n\004body\030\002 \001(\t2Y\n\016O"
      "rleansService\022G\n\007Request\022\031.dodo.test.Orl"
      "eansRequest\032\032.dodo.test.OrleansResponse\""
      "\005\320\363\030\235\022P\000P\001b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 378);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "orleans_service.proto", &protobuf_RegisterTypes);
  ::protobuf_gayrpc_2fcore_2fgayrpc_5foption_2eproto::AddDescriptors();
  ::protobuf_gayrpc_2fcore_2fgayrpc_5fmeta_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_orleans_5fservice_2eproto
namespace dodo {
namespace test {

// ===================================================================

void OrleansRequest::InitAsDefaultInstance() {
  ::dodo::test::_OrleansRequest_default_instance_._instance.get_mutable()->meta_ = const_cast< ::gayrpc::core::RpcMeta*>(
      ::gayrpc::core::RpcMeta::internal_default_instance());
}
void OrleansRequest::clear_meta() {
  if (GetArenaNoVirtual() == NULL && meta_ != NULL) {
    delete meta_;
  }
  meta_ = NULL;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int OrleansRequest::kGrainTypeFieldNumber;
const int OrleansRequest::kGrainNameFieldNumber;
const int OrleansRequest::kMetaFieldNumber;
const int OrleansRequest::kBodyFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

OrleansRequest::OrleansRequest()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_orleans_5fservice_2eproto::InitDefaultsOrleansRequest();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:dodo.test.OrleansRequest)
}
OrleansRequest::OrleansRequest(const OrleansRequest& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  grain_type_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.grain_type().size() > 0) {
    grain_type_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.grain_type_);
  }
  grain_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.grain_name().size() > 0) {
    grain_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.grain_name_);
  }
  body_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.body().size() > 0) {
    body_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.body_);
  }
  if (from.has_meta()) {
    meta_ = new ::gayrpc::core::RpcMeta(*from.meta_);
  } else {
    meta_ = NULL;
  }
  // @@protoc_insertion_point(copy_constructor:dodo.test.OrleansRequest)
}

void OrleansRequest::SharedCtor() {
  grain_type_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  grain_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  body_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  meta_ = NULL;
  _cached_size_ = 0;
}

OrleansRequest::~OrleansRequest() {
  // @@protoc_insertion_point(destructor:dodo.test.OrleansRequest)
  SharedDtor();
}

void OrleansRequest::SharedDtor() {
  grain_type_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  grain_name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  body_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete meta_;
}

void OrleansRequest::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* OrleansRequest::descriptor() {
  ::protobuf_orleans_5fservice_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_orleans_5fservice_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const OrleansRequest& OrleansRequest::default_instance() {
  ::protobuf_orleans_5fservice_2eproto::InitDefaultsOrleansRequest();
  return *internal_default_instance();
}

OrleansRequest* OrleansRequest::New(::google::protobuf::Arena* arena) const {
  OrleansRequest* n = new OrleansRequest;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void OrleansRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:dodo.test.OrleansRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  grain_type_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  grain_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  body_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (GetArenaNoVirtual() == NULL && meta_ != NULL) {
    delete meta_;
  }
  meta_ = NULL;
  _internal_metadata_.Clear();
}

bool OrleansRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:dodo.test.OrleansRequest)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string grain_type = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_grain_type()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->grain_type().data(), static_cast<int>(this->grain_type().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "dodo.test.OrleansRequest.grain_type"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string grain_name = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_grain_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->grain_name().data(), static_cast<int>(this->grain_name().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "dodo.test.OrleansRequest.grain_name"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .gayrpc.core.RpcMeta meta = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_meta()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string body = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_body()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->body().data(), static_cast<int>(this->body().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "dodo.test.OrleansRequest.body"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:dodo.test.OrleansRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:dodo.test.OrleansRequest)
  return false;
#undef DO_
}

void OrleansRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:dodo.test.OrleansRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string grain_type = 1;
  if (this->grain_type().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->grain_type().data(), static_cast<int>(this->grain_type().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "dodo.test.OrleansRequest.grain_type");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->grain_type(), output);
  }

  // string grain_name = 2;
  if (this->grain_name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->grain_name().data(), static_cast<int>(this->grain_name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "dodo.test.OrleansRequest.grain_name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->grain_name(), output);
  }

  // .gayrpc.core.RpcMeta meta = 3;
  if (this->has_meta()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, *this->meta_, output);
  }

  // string body = 4;
  if (this->body().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->body().data(), static_cast<int>(this->body().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "dodo.test.OrleansRequest.body");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->body(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:dodo.test.OrleansRequest)
}

::google::protobuf::uint8* OrleansRequest::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:dodo.test.OrleansRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string grain_type = 1;
  if (this->grain_type().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->grain_type().data(), static_cast<int>(this->grain_type().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "dodo.test.OrleansRequest.grain_type");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->grain_type(), target);
  }

  // string grain_name = 2;
  if (this->grain_name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->grain_name().data(), static_cast<int>(this->grain_name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "dodo.test.OrleansRequest.grain_name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->grain_name(), target);
  }

  // .gayrpc.core.RpcMeta meta = 3;
  if (this->has_meta()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        3, *this->meta_, deterministic, target);
  }

  // string body = 4;
  if (this->body().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->body().data(), static_cast<int>(this->body().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "dodo.test.OrleansRequest.body");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->body(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:dodo.test.OrleansRequest)
  return target;
}

size_t OrleansRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:dodo.test.OrleansRequest)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string grain_type = 1;
  if (this->grain_type().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->grain_type());
  }

  // string grain_name = 2;
  if (this->grain_name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->grain_name());
  }

  // string body = 4;
  if (this->body().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->body());
  }

  // .gayrpc.core.RpcMeta meta = 3;
  if (this->has_meta()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *this->meta_);
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void OrleansRequest::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:dodo.test.OrleansRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const OrleansRequest* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const OrleansRequest>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:dodo.test.OrleansRequest)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:dodo.test.OrleansRequest)
    MergeFrom(*source);
  }
}

void OrleansRequest::MergeFrom(const OrleansRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:dodo.test.OrleansRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.grain_type().size() > 0) {

    grain_type_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.grain_type_);
  }
  if (from.grain_name().size() > 0) {

    grain_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.grain_name_);
  }
  if (from.body().size() > 0) {

    body_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.body_);
  }
  if (from.has_meta()) {
    mutable_meta()->::gayrpc::core::RpcMeta::MergeFrom(from.meta());
  }
}

void OrleansRequest::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:dodo.test.OrleansRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void OrleansRequest::CopyFrom(const OrleansRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:dodo.test.OrleansRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool OrleansRequest::IsInitialized() const {
  return true;
}

void OrleansRequest::Swap(OrleansRequest* other) {
  if (other == this) return;
  InternalSwap(other);
}
void OrleansRequest::InternalSwap(OrleansRequest* other) {
  using std::swap;
  grain_type_.Swap(&other->grain_type_);
  grain_name_.Swap(&other->grain_name_);
  body_.Swap(&other->body_);
  swap(meta_, other->meta_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata OrleansRequest::GetMetadata() const {
  protobuf_orleans_5fservice_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_orleans_5fservice_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void OrleansResponse::InitAsDefaultInstance() {
  ::dodo::test::_OrleansResponse_default_instance_._instance.get_mutable()->meta_ = const_cast< ::gayrpc::core::RpcMeta*>(
      ::gayrpc::core::RpcMeta::internal_default_instance());
}
void OrleansResponse::clear_meta() {
  if (GetArenaNoVirtual() == NULL && meta_ != NULL) {
    delete meta_;
  }
  meta_ = NULL;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int OrleansResponse::kMetaFieldNumber;
const int OrleansResponse::kBodyFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

OrleansResponse::OrleansResponse()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_orleans_5fservice_2eproto::InitDefaultsOrleansResponse();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:dodo.test.OrleansResponse)
}
OrleansResponse::OrleansResponse(const OrleansResponse& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  body_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.body().size() > 0) {
    body_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.body_);
  }
  if (from.has_meta()) {
    meta_ = new ::gayrpc::core::RpcMeta(*from.meta_);
  } else {
    meta_ = NULL;
  }
  // @@protoc_insertion_point(copy_constructor:dodo.test.OrleansResponse)
}

void OrleansResponse::SharedCtor() {
  body_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  meta_ = NULL;
  _cached_size_ = 0;
}

OrleansResponse::~OrleansResponse() {
  // @@protoc_insertion_point(destructor:dodo.test.OrleansResponse)
  SharedDtor();
}

void OrleansResponse::SharedDtor() {
  body_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete meta_;
}

void OrleansResponse::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* OrleansResponse::descriptor() {
  ::protobuf_orleans_5fservice_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_orleans_5fservice_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const OrleansResponse& OrleansResponse::default_instance() {
  ::protobuf_orleans_5fservice_2eproto::InitDefaultsOrleansResponse();
  return *internal_default_instance();
}

OrleansResponse* OrleansResponse::New(::google::protobuf::Arena* arena) const {
  OrleansResponse* n = new OrleansResponse;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void OrleansResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:dodo.test.OrleansResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  body_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (GetArenaNoVirtual() == NULL && meta_ != NULL) {
    delete meta_;
  }
  meta_ = NULL;
  _internal_metadata_.Clear();
}

bool OrleansResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:dodo.test.OrleansResponse)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .gayrpc.core.RpcMeta meta = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_meta()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string body = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_body()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->body().data(), static_cast<int>(this->body().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "dodo.test.OrleansResponse.body"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:dodo.test.OrleansResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:dodo.test.OrleansResponse)
  return false;
#undef DO_
}

void OrleansResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:dodo.test.OrleansResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .gayrpc.core.RpcMeta meta = 1;
  if (this->has_meta()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, *this->meta_, output);
  }

  // string body = 2;
  if (this->body().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->body().data(), static_cast<int>(this->body().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "dodo.test.OrleansResponse.body");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->body(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:dodo.test.OrleansResponse)
}

::google::protobuf::uint8* OrleansResponse::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:dodo.test.OrleansResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .gayrpc.core.RpcMeta meta = 1;
  if (this->has_meta()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, *this->meta_, deterministic, target);
  }

  // string body = 2;
  if (this->body().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->body().data(), static_cast<int>(this->body().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "dodo.test.OrleansResponse.body");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->body(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:dodo.test.OrleansResponse)
  return target;
}

size_t OrleansResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:dodo.test.OrleansResponse)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string body = 2;
  if (this->body().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->body());
  }

  // .gayrpc.core.RpcMeta meta = 1;
  if (this->has_meta()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *this->meta_);
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void OrleansResponse::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:dodo.test.OrleansResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const OrleansResponse* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const OrleansResponse>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:dodo.test.OrleansResponse)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:dodo.test.OrleansResponse)
    MergeFrom(*source);
  }
}

void OrleansResponse::MergeFrom(const OrleansResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:dodo.test.OrleansResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.body().size() > 0) {

    body_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.body_);
  }
  if (from.has_meta()) {
    mutable_meta()->::gayrpc::core::RpcMeta::MergeFrom(from.meta());
  }
}

void OrleansResponse::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:dodo.test.OrleansResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void OrleansResponse::CopyFrom(const OrleansResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:dodo.test.OrleansResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool OrleansResponse::IsInitialized() const {
  return true;
}

void OrleansResponse::Swap(OrleansResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void OrleansResponse::InternalSwap(OrleansResponse* other) {
  using std::swap;
  body_.Swap(&other->body_);
  swap(meta_, other->meta_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata OrleansResponse::GetMetadata() const {
  protobuf_orleans_5fservice_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_orleans_5fservice_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace test
}  // namespace dodo

// @@protoc_insertion_point(global_scope)
