// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gayrpc/core/gayrpc_meta.proto

#include "gayrpc/core/gayrpc_meta.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_gayrpc_2fcore_2fgayrpc_5fmeta_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_RpcMeta_MetaDataEntry_DoNotUse_gayrpc_2fcore_2fgayrpc_5fmeta_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_gayrpc_2fcore_2fgayrpc_5fmeta_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_RpcMeta_Request_gayrpc_2fcore_2fgayrpc_5fmeta_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_gayrpc_2fcore_2fgayrpc_5fmeta_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_RpcMeta_Response_gayrpc_2fcore_2fgayrpc_5fmeta_2eproto;
namespace gayrpc {
namespace core {
class RpcMeta_RequestDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<RpcMeta_Request> _instance;
} _RpcMeta_Request_default_instance_;
class RpcMeta_ResponseDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<RpcMeta_Response> _instance;
} _RpcMeta_Response_default_instance_;
class RpcMeta_MetaDataEntry_DoNotUseDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<RpcMeta_MetaDataEntry_DoNotUse> _instance;
} _RpcMeta_MetaDataEntry_DoNotUse_default_instance_;
class RpcMetaDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<RpcMeta> _instance;
} _RpcMeta_default_instance_;
}  // namespace core
}  // namespace gayrpc
static void InitDefaultsscc_info_RpcMeta_gayrpc_2fcore_2fgayrpc_5fmeta_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::gayrpc::core::_RpcMeta_default_instance_;
    new (ptr) ::gayrpc::core::RpcMeta();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::gayrpc::core::RpcMeta::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<3> scc_info_RpcMeta_gayrpc_2fcore_2fgayrpc_5fmeta_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 3, 0, InitDefaultsscc_info_RpcMeta_gayrpc_2fcore_2fgayrpc_5fmeta_2eproto}, {
      &scc_info_RpcMeta_Request_gayrpc_2fcore_2fgayrpc_5fmeta_2eproto.base,
      &scc_info_RpcMeta_Response_gayrpc_2fcore_2fgayrpc_5fmeta_2eproto.base,
      &scc_info_RpcMeta_MetaDataEntry_DoNotUse_gayrpc_2fcore_2fgayrpc_5fmeta_2eproto.base,}};

static void InitDefaultsscc_info_RpcMeta_MetaDataEntry_DoNotUse_gayrpc_2fcore_2fgayrpc_5fmeta_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::gayrpc::core::_RpcMeta_MetaDataEntry_DoNotUse_default_instance_;
    new (ptr) ::gayrpc::core::RpcMeta_MetaDataEntry_DoNotUse();
  }
  ::gayrpc::core::RpcMeta_MetaDataEntry_DoNotUse::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_RpcMeta_MetaDataEntry_DoNotUse_gayrpc_2fcore_2fgayrpc_5fmeta_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_RpcMeta_MetaDataEntry_DoNotUse_gayrpc_2fcore_2fgayrpc_5fmeta_2eproto}, {}};

static void InitDefaultsscc_info_RpcMeta_Request_gayrpc_2fcore_2fgayrpc_5fmeta_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::gayrpc::core::_RpcMeta_Request_default_instance_;
    new (ptr) ::gayrpc::core::RpcMeta_Request();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::gayrpc::core::RpcMeta_Request::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_RpcMeta_Request_gayrpc_2fcore_2fgayrpc_5fmeta_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_RpcMeta_Request_gayrpc_2fcore_2fgayrpc_5fmeta_2eproto}, {}};

static void InitDefaultsscc_info_RpcMeta_Response_gayrpc_2fcore_2fgayrpc_5fmeta_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::gayrpc::core::_RpcMeta_Response_default_instance_;
    new (ptr) ::gayrpc::core::RpcMeta_Response();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::gayrpc::core::RpcMeta_Response::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_RpcMeta_Response_gayrpc_2fcore_2fgayrpc_5fmeta_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_RpcMeta_Response_gayrpc_2fcore_2fgayrpc_5fmeta_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_gayrpc_2fcore_2fgayrpc_5fmeta_2eproto[4];
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_gayrpc_2fcore_2fgayrpc_5fmeta_2eproto[2];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_gayrpc_2fcore_2fgayrpc_5fmeta_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_gayrpc_2fcore_2fgayrpc_5fmeta_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::gayrpc::core::RpcMeta_Request, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::gayrpc::core::RpcMeta_Request, intmethod_),
  PROTOBUF_FIELD_OFFSET(::gayrpc::core::RpcMeta_Request, strmethod_),
  PROTOBUF_FIELD_OFFSET(::gayrpc::core::RpcMeta_Request, expect_response_),
  PROTOBUF_FIELD_OFFSET(::gayrpc::core::RpcMeta_Request, sequence_id_),
  PROTOBUF_FIELD_OFFSET(::gayrpc::core::RpcMeta_Request, timeout_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::gayrpc::core::RpcMeta_Response, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::gayrpc::core::RpcMeta_Response, sequence_id_),
  PROTOBUF_FIELD_OFFSET(::gayrpc::core::RpcMeta_Response, failed_),
  PROTOBUF_FIELD_OFFSET(::gayrpc::core::RpcMeta_Response, error_code_),
  PROTOBUF_FIELD_OFFSET(::gayrpc::core::RpcMeta_Response, reason_),
  PROTOBUF_FIELD_OFFSET(::gayrpc::core::RpcMeta_Response, timeout_),
  PROTOBUF_FIELD_OFFSET(::gayrpc::core::RpcMeta_MetaDataEntry_DoNotUse, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::gayrpc::core::RpcMeta_MetaDataEntry_DoNotUse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::gayrpc::core::RpcMeta_MetaDataEntry_DoNotUse, key_),
  PROTOBUF_FIELD_OFFSET(::gayrpc::core::RpcMeta_MetaDataEntry_DoNotUse, value_),
  0,
  1,
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::gayrpc::core::RpcMeta, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::gayrpc::core::RpcMeta, type_),
  PROTOBUF_FIELD_OFFSET(::gayrpc::core::RpcMeta, service_id_),
  PROTOBUF_FIELD_OFFSET(::gayrpc::core::RpcMeta, encoding_),
  PROTOBUF_FIELD_OFFSET(::gayrpc::core::RpcMeta, request_info_),
  PROTOBUF_FIELD_OFFSET(::gayrpc::core::RpcMeta, response_info_),
  PROTOBUF_FIELD_OFFSET(::gayrpc::core::RpcMeta, meta_data_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::gayrpc::core::RpcMeta_Request)},
  { 10, -1, sizeof(::gayrpc::core::RpcMeta_Response)},
  { 20, 27, sizeof(::gayrpc::core::RpcMeta_MetaDataEntry_DoNotUse)},
  { 29, -1, sizeof(::gayrpc::core::RpcMeta)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::gayrpc::core::_RpcMeta_Request_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::gayrpc::core::_RpcMeta_Response_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::gayrpc::core::_RpcMeta_MetaDataEntry_DoNotUse_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::gayrpc::core::_RpcMeta_default_instance_),
};

const char descriptor_table_protodef_gayrpc_2fcore_2fgayrpc_5fmeta_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\035gayrpc/core/gayrpc_meta.proto\022\013gayrpc."
  "core\"\364\004\n\007RpcMeta\022\'\n\004type\030\001 \001(\0162\031.gayrpc."
  "core.RpcMeta.Type\022\022\n\nservice_id\030\002 \001(\r\0227\n"
  "\010encoding\030\003 \001(\0162%.gayrpc.core.RpcMeta.Da"
  "taEncodingType\0222\n\014request_info\030\004 \001(\0132\034.g"
  "ayrpc.core.RpcMeta.Request\0224\n\rresponse_i"
  "nfo\030\005 \001(\0132\035.gayrpc.core.RpcMeta.Response"
  "\0225\n\tmeta_data\030\006 \003(\0132\".gayrpc.core.RpcMet"
  "a.MetaDataEntry\032n\n\007Request\022\021\n\tintMethod\030"
  "\001 \001(\004\022\021\n\tstrMethod\030\002 \001(\t\022\027\n\017expect_respo"
  "nse\030\003 \001(\010\022\023\n\013sequence_id\030\004 \001(\004\022\017\n\007timeou"
  "t\030\005 \001(\004\032d\n\010Response\022\023\n\013sequence_id\030\001 \001(\004"
  "\022\016\n\006failed\030\002 \001(\010\022\022\n\nerror_code\030\003 \001(\005\022\016\n\006"
  "reason\030\004 \001(\t\022\017\n\007timeout\030\005 \001(\010\032/\n\rMetaDat"
  "aEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"!"
  "\n\004Type\022\013\n\007REQUEST\020\000\022\014\n\010RESPONSE\020\001\"(\n\020Dat"
  "aEncodingType\022\n\n\006BINARY\020\000\022\010\n\004JSON\020\001b\006pro"
  "to3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_gayrpc_2fcore_2fgayrpc_5fmeta_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_gayrpc_2fcore_2fgayrpc_5fmeta_2eproto_sccs[4] = {
  &scc_info_RpcMeta_gayrpc_2fcore_2fgayrpc_5fmeta_2eproto.base,
  &scc_info_RpcMeta_MetaDataEntry_DoNotUse_gayrpc_2fcore_2fgayrpc_5fmeta_2eproto.base,
  &scc_info_RpcMeta_Request_gayrpc_2fcore_2fgayrpc_5fmeta_2eproto.base,
  &scc_info_RpcMeta_Response_gayrpc_2fcore_2fgayrpc_5fmeta_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_gayrpc_2fcore_2fgayrpc_5fmeta_2eproto_once;
static bool descriptor_table_gayrpc_2fcore_2fgayrpc_5fmeta_2eproto_initialized = false;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_gayrpc_2fcore_2fgayrpc_5fmeta_2eproto = {
  &descriptor_table_gayrpc_2fcore_2fgayrpc_5fmeta_2eproto_initialized, descriptor_table_protodef_gayrpc_2fcore_2fgayrpc_5fmeta_2eproto, "gayrpc/core/gayrpc_meta.proto", 683,
  &descriptor_table_gayrpc_2fcore_2fgayrpc_5fmeta_2eproto_once, descriptor_table_gayrpc_2fcore_2fgayrpc_5fmeta_2eproto_sccs, descriptor_table_gayrpc_2fcore_2fgayrpc_5fmeta_2eproto_deps, 4, 0,
  schemas, file_default_instances, TableStruct_gayrpc_2fcore_2fgayrpc_5fmeta_2eproto::offsets,
  file_level_metadata_gayrpc_2fcore_2fgayrpc_5fmeta_2eproto, 4, file_level_enum_descriptors_gayrpc_2fcore_2fgayrpc_5fmeta_2eproto, file_level_service_descriptors_gayrpc_2fcore_2fgayrpc_5fmeta_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_gayrpc_2fcore_2fgayrpc_5fmeta_2eproto = (  ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_gayrpc_2fcore_2fgayrpc_5fmeta_2eproto), true);
namespace gayrpc {
namespace core {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* RpcMeta_Type_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_gayrpc_2fcore_2fgayrpc_5fmeta_2eproto);
  return file_level_enum_descriptors_gayrpc_2fcore_2fgayrpc_5fmeta_2eproto[0];
}
bool RpcMeta_Type_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

#if (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)
constexpr RpcMeta_Type RpcMeta::REQUEST;
constexpr RpcMeta_Type RpcMeta::RESPONSE;
constexpr RpcMeta_Type RpcMeta::Type_MIN;
constexpr RpcMeta_Type RpcMeta::Type_MAX;
constexpr int RpcMeta::Type_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* RpcMeta_DataEncodingType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_gayrpc_2fcore_2fgayrpc_5fmeta_2eproto);
  return file_level_enum_descriptors_gayrpc_2fcore_2fgayrpc_5fmeta_2eproto[1];
}
bool RpcMeta_DataEncodingType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

#if (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)
constexpr RpcMeta_DataEncodingType RpcMeta::BINARY;
constexpr RpcMeta_DataEncodingType RpcMeta::JSON;
constexpr RpcMeta_DataEncodingType RpcMeta::DataEncodingType_MIN;
constexpr RpcMeta_DataEncodingType RpcMeta::DataEncodingType_MAX;
constexpr int RpcMeta::DataEncodingType_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || _MSC_VER >= 1900)

// ===================================================================

void RpcMeta_Request::InitAsDefaultInstance() {
}
class RpcMeta_Request::_Internal {
 public:
};

RpcMeta_Request::RpcMeta_Request()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:gayrpc.core.RpcMeta.Request)
}
RpcMeta_Request::RpcMeta_Request(const RpcMeta_Request& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  strmethod_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_strmethod().empty()) {
    strmethod_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.strmethod_);
  }
  ::memcpy(&intmethod_, &from.intmethod_,
    static_cast<size_t>(reinterpret_cast<char*>(&expect_response_) -
    reinterpret_cast<char*>(&intmethod_)) + sizeof(expect_response_));
  // @@protoc_insertion_point(copy_constructor:gayrpc.core.RpcMeta.Request)
}

void RpcMeta_Request::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_RpcMeta_Request_gayrpc_2fcore_2fgayrpc_5fmeta_2eproto.base);
  strmethod_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&intmethod_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&expect_response_) -
      reinterpret_cast<char*>(&intmethod_)) + sizeof(expect_response_));
}

RpcMeta_Request::~RpcMeta_Request() {
  // @@protoc_insertion_point(destructor:gayrpc.core.RpcMeta.Request)
  SharedDtor();
}

void RpcMeta_Request::SharedDtor() {
  strmethod_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void RpcMeta_Request::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const RpcMeta_Request& RpcMeta_Request::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_RpcMeta_Request_gayrpc_2fcore_2fgayrpc_5fmeta_2eproto.base);
  return *internal_default_instance();
}


void RpcMeta_Request::Clear() {
// @@protoc_insertion_point(message_clear_start:gayrpc.core.RpcMeta.Request)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  strmethod_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&intmethod_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&expect_response_) -
      reinterpret_cast<char*>(&intmethod_)) + sizeof(expect_response_));
  _internal_metadata_.Clear();
}

const char* RpcMeta_Request::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // uint64 intMethod = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          intmethod_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string strMethod = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParserUTF8(_internal_mutable_strmethod(), ptr, ctx, "gayrpc.core.RpcMeta.Request.strMethod");
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bool expect_response = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          expect_response_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint64 sequence_id = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 32)) {
          sequence_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint64 timeout = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 40)) {
          timeout_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* RpcMeta_Request::InternalSerializeWithCachedSizesToArray(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:gayrpc.core.RpcMeta.Request)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 intMethod = 1;
  if (this->intmethod() != 0) {
    stream->EnsureSpace(&target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt64ToArray(1, this->_internal_intmethod(), target);
  }

  // string strMethod = 2;
  if (this->strmethod().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_strmethod().data(), static_cast<int>(this->_internal_strmethod().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "gayrpc.core.RpcMeta.Request.strMethod");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_strmethod(), target);
  }

  // bool expect_response = 3;
  if (this->expect_response() != 0) {
    stream->EnsureSpace(&target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(3, this->_internal_expect_response(), target);
  }

  // uint64 sequence_id = 4;
  if (this->sequence_id() != 0) {
    stream->EnsureSpace(&target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt64ToArray(4, this->_internal_sequence_id(), target);
  }

  // uint64 timeout = 5;
  if (this->timeout() != 0) {
    stream->EnsureSpace(&target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt64ToArray(5, this->_internal_timeout(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:gayrpc.core.RpcMeta.Request)
  return target;
}

size_t RpcMeta_Request::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:gayrpc.core.RpcMeta.Request)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string strMethod = 2;
  if (this->strmethod().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_strmethod());
  }

  // uint64 intMethod = 1;
  if (this->intmethod() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt64Size(
        this->_internal_intmethod());
  }

  // uint64 sequence_id = 4;
  if (this->sequence_id() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt64Size(
        this->_internal_sequence_id());
  }

  // uint64 timeout = 5;
  if (this->timeout() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt64Size(
        this->_internal_timeout());
  }

  // bool expect_response = 3;
  if (this->expect_response() != 0) {
    total_size += 1 + 1;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void RpcMeta_Request::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:gayrpc.core.RpcMeta.Request)
  GOOGLE_DCHECK_NE(&from, this);
  const RpcMeta_Request* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<RpcMeta_Request>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:gayrpc.core.RpcMeta.Request)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:gayrpc.core.RpcMeta.Request)
    MergeFrom(*source);
  }
}

void RpcMeta_Request::MergeFrom(const RpcMeta_Request& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:gayrpc.core.RpcMeta.Request)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.strmethod().size() > 0) {

    strmethod_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.strmethod_);
  }
  if (from.intmethod() != 0) {
    _internal_set_intmethod(from._internal_intmethod());
  }
  if (from.sequence_id() != 0) {
    _internal_set_sequence_id(from._internal_sequence_id());
  }
  if (from.timeout() != 0) {
    _internal_set_timeout(from._internal_timeout());
  }
  if (from.expect_response() != 0) {
    _internal_set_expect_response(from._internal_expect_response());
  }
}

void RpcMeta_Request::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:gayrpc.core.RpcMeta.Request)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void RpcMeta_Request::CopyFrom(const RpcMeta_Request& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:gayrpc.core.RpcMeta.Request)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RpcMeta_Request::IsInitialized() const {
  return true;
}

void RpcMeta_Request::InternalSwap(RpcMeta_Request* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  strmethod_.Swap(&other->strmethod_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(intmethod_, other->intmethod_);
  swap(sequence_id_, other->sequence_id_);
  swap(timeout_, other->timeout_);
  swap(expect_response_, other->expect_response_);
}

::PROTOBUF_NAMESPACE_ID::Metadata RpcMeta_Request::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void RpcMeta_Response::InitAsDefaultInstance() {
}
class RpcMeta_Response::_Internal {
 public:
};

RpcMeta_Response::RpcMeta_Response()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:gayrpc.core.RpcMeta.Response)
}
RpcMeta_Response::RpcMeta_Response(const RpcMeta_Response& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  reason_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_reason().empty()) {
    reason_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.reason_);
  }
  ::memcpy(&sequence_id_, &from.sequence_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&timeout_) -
    reinterpret_cast<char*>(&sequence_id_)) + sizeof(timeout_));
  // @@protoc_insertion_point(copy_constructor:gayrpc.core.RpcMeta.Response)
}

void RpcMeta_Response::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_RpcMeta_Response_gayrpc_2fcore_2fgayrpc_5fmeta_2eproto.base);
  reason_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&sequence_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&timeout_) -
      reinterpret_cast<char*>(&sequence_id_)) + sizeof(timeout_));
}

RpcMeta_Response::~RpcMeta_Response() {
  // @@protoc_insertion_point(destructor:gayrpc.core.RpcMeta.Response)
  SharedDtor();
}

void RpcMeta_Response::SharedDtor() {
  reason_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void RpcMeta_Response::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const RpcMeta_Response& RpcMeta_Response::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_RpcMeta_Response_gayrpc_2fcore_2fgayrpc_5fmeta_2eproto.base);
  return *internal_default_instance();
}


void RpcMeta_Response::Clear() {
// @@protoc_insertion_point(message_clear_start:gayrpc.core.RpcMeta.Response)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  reason_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&sequence_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&timeout_) -
      reinterpret_cast<char*>(&sequence_id_)) + sizeof(timeout_));
  _internal_metadata_.Clear();
}

const char* RpcMeta_Response::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // uint64 sequence_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          sequence_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bool failed = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          failed_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 error_code = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          error_code_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string reason = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParserUTF8(_internal_mutable_reason(), ptr, ctx, "gayrpc.core.RpcMeta.Response.reason");
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bool timeout = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 40)) {
          timeout_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* RpcMeta_Response::InternalSerializeWithCachedSizesToArray(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:gayrpc.core.RpcMeta.Response)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 sequence_id = 1;
  if (this->sequence_id() != 0) {
    stream->EnsureSpace(&target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt64ToArray(1, this->_internal_sequence_id(), target);
  }

  // bool failed = 2;
  if (this->failed() != 0) {
    stream->EnsureSpace(&target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(2, this->_internal_failed(), target);
  }

  // int32 error_code = 3;
  if (this->error_code() != 0) {
    stream->EnsureSpace(&target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(3, this->_internal_error_code(), target);
  }

  // string reason = 4;
  if (this->reason().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_reason().data(), static_cast<int>(this->_internal_reason().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "gayrpc.core.RpcMeta.Response.reason");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_reason(), target);
  }

  // bool timeout = 5;
  if (this->timeout() != 0) {
    stream->EnsureSpace(&target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(5, this->_internal_timeout(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:gayrpc.core.RpcMeta.Response)
  return target;
}

size_t RpcMeta_Response::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:gayrpc.core.RpcMeta.Response)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string reason = 4;
  if (this->reason().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_reason());
  }

  // uint64 sequence_id = 1;
  if (this->sequence_id() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt64Size(
        this->_internal_sequence_id());
  }

  // int32 error_code = 3;
  if (this->error_code() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_error_code());
  }

  // bool failed = 2;
  if (this->failed() != 0) {
    total_size += 1 + 1;
  }

  // bool timeout = 5;
  if (this->timeout() != 0) {
    total_size += 1 + 1;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void RpcMeta_Response::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:gayrpc.core.RpcMeta.Response)
  GOOGLE_DCHECK_NE(&from, this);
  const RpcMeta_Response* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<RpcMeta_Response>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:gayrpc.core.RpcMeta.Response)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:gayrpc.core.RpcMeta.Response)
    MergeFrom(*source);
  }
}

void RpcMeta_Response::MergeFrom(const RpcMeta_Response& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:gayrpc.core.RpcMeta.Response)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.reason().size() > 0) {

    reason_.AssignWithDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from.reason_);
  }
  if (from.sequence_id() != 0) {
    _internal_set_sequence_id(from._internal_sequence_id());
  }
  if (from.error_code() != 0) {
    _internal_set_error_code(from._internal_error_code());
  }
  if (from.failed() != 0) {
    _internal_set_failed(from._internal_failed());
  }
  if (from.timeout() != 0) {
    _internal_set_timeout(from._internal_timeout());
  }
}

void RpcMeta_Response::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:gayrpc.core.RpcMeta.Response)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void RpcMeta_Response::CopyFrom(const RpcMeta_Response& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:gayrpc.core.RpcMeta.Response)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RpcMeta_Response::IsInitialized() const {
  return true;
}

void RpcMeta_Response::InternalSwap(RpcMeta_Response* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  reason_.Swap(&other->reason_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(sequence_id_, other->sequence_id_);
  swap(error_code_, other->error_code_);
  swap(failed_, other->failed_);
  swap(timeout_, other->timeout_);
}

::PROTOBUF_NAMESPACE_ID::Metadata RpcMeta_Response::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

RpcMeta_MetaDataEntry_DoNotUse::RpcMeta_MetaDataEntry_DoNotUse() {}
RpcMeta_MetaDataEntry_DoNotUse::RpcMeta_MetaDataEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
    : SuperType(arena) {}
void RpcMeta_MetaDataEntry_DoNotUse::MergeFrom(const RpcMeta_MetaDataEntry_DoNotUse& other) {
  MergeFromInternal(other);
}
::PROTOBUF_NAMESPACE_ID::Metadata RpcMeta_MetaDataEntry_DoNotUse::GetMetadata() const {
  return GetMetadataStatic();
}
void RpcMeta_MetaDataEntry_DoNotUse::MergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::Message& other) {
  ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom(other);
}


// ===================================================================

void RpcMeta::InitAsDefaultInstance() {
  ::gayrpc::core::_RpcMeta_default_instance_._instance.get_mutable()->request_info_ = const_cast< ::gayrpc::core::RpcMeta_Request*>(
      ::gayrpc::core::RpcMeta_Request::internal_default_instance());
  ::gayrpc::core::_RpcMeta_default_instance_._instance.get_mutable()->response_info_ = const_cast< ::gayrpc::core::RpcMeta_Response*>(
      ::gayrpc::core::RpcMeta_Response::internal_default_instance());
}
class RpcMeta::_Internal {
 public:
  static const ::gayrpc::core::RpcMeta_Request& request_info(const RpcMeta* msg);
  static const ::gayrpc::core::RpcMeta_Response& response_info(const RpcMeta* msg);
};

const ::gayrpc::core::RpcMeta_Request&
RpcMeta::_Internal::request_info(const RpcMeta* msg) {
  return *msg->request_info_;
}
const ::gayrpc::core::RpcMeta_Response&
RpcMeta::_Internal::response_info(const RpcMeta* msg) {
  return *msg->response_info_;
}
RpcMeta::RpcMeta()
  : ::PROTOBUF_NAMESPACE_ID::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:gayrpc.core.RpcMeta)
}
RpcMeta::RpcMeta(const RpcMeta& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  meta_data_.MergeFrom(from.meta_data_);
  if (from._internal_has_request_info()) {
    request_info_ = new ::gayrpc::core::RpcMeta_Request(*from.request_info_);
  } else {
    request_info_ = nullptr;
  }
  if (from._internal_has_response_info()) {
    response_info_ = new ::gayrpc::core::RpcMeta_Response(*from.response_info_);
  } else {
    response_info_ = nullptr;
  }
  ::memcpy(&type_, &from.type_,
    static_cast<size_t>(reinterpret_cast<char*>(&encoding_) -
    reinterpret_cast<char*>(&type_)) + sizeof(encoding_));
  // @@protoc_insertion_point(copy_constructor:gayrpc.core.RpcMeta)
}

void RpcMeta::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_RpcMeta_gayrpc_2fcore_2fgayrpc_5fmeta_2eproto.base);
  ::memset(&request_info_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&encoding_) -
      reinterpret_cast<char*>(&request_info_)) + sizeof(encoding_));
}

RpcMeta::~RpcMeta() {
  // @@protoc_insertion_point(destructor:gayrpc.core.RpcMeta)
  SharedDtor();
}

void RpcMeta::SharedDtor() {
  if (this != internal_default_instance()) delete request_info_;
  if (this != internal_default_instance()) delete response_info_;
}

void RpcMeta::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const RpcMeta& RpcMeta::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_RpcMeta_gayrpc_2fcore_2fgayrpc_5fmeta_2eproto.base);
  return *internal_default_instance();
}


void RpcMeta::Clear() {
// @@protoc_insertion_point(message_clear_start:gayrpc.core.RpcMeta)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  meta_data_.Clear();
  if (GetArenaNoVirtual() == nullptr && request_info_ != nullptr) {
    delete request_info_;
  }
  request_info_ = nullptr;
  if (GetArenaNoVirtual() == nullptr && response_info_ != nullptr) {
    delete response_info_;
  }
  response_info_ = nullptr;
  ::memset(&type_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&encoding_) -
      reinterpret_cast<char*>(&type_)) + sizeof(encoding_));
  _internal_metadata_.Clear();
}

const char* RpcMeta::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // .gayrpc.core.RpcMeta.Type type = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
          _internal_set_type(static_cast<::gayrpc::core::RpcMeta_Type>(val));
        } else goto handle_unusual;
        continue;
      // uint32 service_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          service_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .gayrpc.core.RpcMeta.DataEncodingType encoding = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint(&ptr);
          CHK_(ptr);
          _internal_set_encoding(static_cast<::gayrpc::core::RpcMeta_DataEncodingType>(val));
        } else goto handle_unusual;
        continue;
      // .gayrpc.core.RpcMeta.Request request_info = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          ptr = ctx->ParseMessage(_internal_mutable_request_info(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .gayrpc.core.RpcMeta.Response response_info = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 42)) {
          ptr = ctx->ParseMessage(_internal_mutable_response_info(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // map<string, string> meta_data = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 50)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(&meta_data_, ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<50>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag, &_internal_metadata_, ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* RpcMeta::InternalSerializeWithCachedSizesToArray(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:gayrpc.core.RpcMeta)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .gayrpc.core.RpcMeta.Type type = 1;
  if (this->type() != 0) {
    stream->EnsureSpace(&target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      1, this->_internal_type(), target);
  }

  // uint32 service_id = 2;
  if (this->service_id() != 0) {
    stream->EnsureSpace(&target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(2, this->_internal_service_id(), target);
  }

  // .gayrpc.core.RpcMeta.DataEncodingType encoding = 3;
  if (this->encoding() != 0) {
    stream->EnsureSpace(&target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      3, this->_internal_encoding(), target);
  }

  // .gayrpc.core.RpcMeta.Request request_info = 4;
  if (this->has_request_info()) {
    stream->EnsureSpace(&target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessageToArray(
        4, _Internal::request_info(this), target, stream);
  }

  // .gayrpc.core.RpcMeta.Response response_info = 5;
  if (this->has_response_info()) {
    stream->EnsureSpace(&target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessageToArray(
        5, _Internal::response_info(this), target, stream);
  }

  // map<string, string> meta_data = 6;
  if (!this->_internal_meta_data().empty()) {
    typedef ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >::const_pointer
        ConstPtr;
    typedef ConstPtr SortItem;
    typedef ::PROTOBUF_NAMESPACE_ID::internal::CompareByDerefFirst<SortItem> Less;
    struct Utf8Check {
      static void Check(ConstPtr p) {
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
          p->first.data(), static_cast<int>(p->first.length()),
          ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
          "gayrpc.core.RpcMeta.MetaDataEntry.key");
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
          p->second.data(), static_cast<int>(p->second.length()),
          ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
          "gayrpc.core.RpcMeta.MetaDataEntry.value");
      }
    };

    if (stream->IsSerializationDeterministic() &&
        this->_internal_meta_data().size() > 1) {
      ::std::unique_ptr<SortItem[]> items(
          new SortItem[this->_internal_meta_data().size()]);
      typedef ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >::size_type size_type;
      size_type n = 0;
      for (::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >::const_iterator
          it = this->_internal_meta_data().begin();
          it != this->_internal_meta_data().end(); ++it, ++n) {
        items[static_cast<ptrdiff_t>(n)] = SortItem(&*it);
      }
      ::std::sort(&items[0], &items[static_cast<ptrdiff_t>(n)], Less());
      for (size_type i = 0; i < n; i++) {
        target = RpcMeta_MetaDataEntry_DoNotUse::Funcs::InternalSerialize(6, items[static_cast<ptrdiff_t>(i)]->first, items[static_cast<ptrdiff_t>(i)]->second, target, stream);
        Utf8Check::Check(&(*items[static_cast<ptrdiff_t>(i)]));
      }
    } else {
      for (::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >::const_iterator
          it = this->_internal_meta_data().begin();
          it != this->_internal_meta_data().end(); ++it) {
        target = RpcMeta_MetaDataEntry_DoNotUse::Funcs::InternalSerialize(6, it->first, it->second, target, stream);
        Utf8Check::Check(&(*it));
      }
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:gayrpc.core.RpcMeta)
  return target;
}

size_t RpcMeta::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:gayrpc.core.RpcMeta)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // map<string, string> meta_data = 6;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(this->_internal_meta_data_size());
  for (::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >::const_iterator
      it = this->_internal_meta_data().begin();
      it != this->_internal_meta_data().end(); ++it) {
    total_size += RpcMeta_MetaDataEntry_DoNotUse::Funcs::ByteSizeLong(it->first, it->second);
  }

  // .gayrpc.core.RpcMeta.Request request_info = 4;
  if (this->has_request_info()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *request_info_);
  }

  // .gayrpc.core.RpcMeta.Response response_info = 5;
  if (this->has_response_info()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *response_info_);
  }

  // .gayrpc.core.RpcMeta.Type type = 1;
  if (this->type() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_type());
  }

  // uint32 service_id = 2;
  if (this->service_id() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_service_id());
  }

  // .gayrpc.core.RpcMeta.DataEncodingType encoding = 3;
  if (this->encoding() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_encoding());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void RpcMeta::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:gayrpc.core.RpcMeta)
  GOOGLE_DCHECK_NE(&from, this);
  const RpcMeta* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<RpcMeta>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:gayrpc.core.RpcMeta)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:gayrpc.core.RpcMeta)
    MergeFrom(*source);
  }
}

void RpcMeta::MergeFrom(const RpcMeta& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:gayrpc.core.RpcMeta)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  meta_data_.MergeFrom(from.meta_data_);
  if (from.has_request_info()) {
    _internal_mutable_request_info()->::gayrpc::core::RpcMeta_Request::MergeFrom(from._internal_request_info());
  }
  if (from.has_response_info()) {
    _internal_mutable_response_info()->::gayrpc::core::RpcMeta_Response::MergeFrom(from._internal_response_info());
  }
  if (from.type() != 0) {
    _internal_set_type(from._internal_type());
  }
  if (from.service_id() != 0) {
    _internal_set_service_id(from._internal_service_id());
  }
  if (from.encoding() != 0) {
    _internal_set_encoding(from._internal_encoding());
  }
}

void RpcMeta::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:gayrpc.core.RpcMeta)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void RpcMeta::CopyFrom(const RpcMeta& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:gayrpc.core.RpcMeta)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RpcMeta::IsInitialized() const {
  return true;
}

void RpcMeta::InternalSwap(RpcMeta* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  meta_data_.Swap(&other->meta_data_);
  swap(request_info_, other->request_info_);
  swap(response_info_, other->response_info_);
  swap(type_, other->type_);
  swap(service_id_, other->service_id_);
  swap(encoding_, other->encoding_);
}

::PROTOBUF_NAMESPACE_ID::Metadata RpcMeta::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace core
}  // namespace gayrpc
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::gayrpc::core::RpcMeta_Request* Arena::CreateMaybeMessage< ::gayrpc::core::RpcMeta_Request >(Arena* arena) {
  return Arena::CreateInternal< ::gayrpc::core::RpcMeta_Request >(arena);
}
template<> PROTOBUF_NOINLINE ::gayrpc::core::RpcMeta_Response* Arena::CreateMaybeMessage< ::gayrpc::core::RpcMeta_Response >(Arena* arena) {
  return Arena::CreateInternal< ::gayrpc::core::RpcMeta_Response >(arena);
}
template<> PROTOBUF_NOINLINE ::gayrpc::core::RpcMeta_MetaDataEntry_DoNotUse* Arena::CreateMaybeMessage< ::gayrpc::core::RpcMeta_MetaDataEntry_DoNotUse >(Arena* arena) {
  return Arena::CreateInternal< ::gayrpc::core::RpcMeta_MetaDataEntry_DoNotUse >(arena);
}
template<> PROTOBUF_NOINLINE ::gayrpc::core::RpcMeta* Arena::CreateMaybeMessage< ::gayrpc::core::RpcMeta >(Arena* arena) {
  return Arena::CreateInternal< ::gayrpc::core::RpcMeta >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
